version: '3.8' # Versão do Docker Compose
services:
  db:
    image: ${DATABASE_IMAGE} # Imagem do banco de dados
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE} # Banco de dados
      MYSQL_USER: ${DATABASE_USER} # Usuário do banco de dados
      MYSQL_PASSWORD: ${DATABASE_PASSWORD} # Senha do banco de dados
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} # Senha root do banco de dados
    ports:
      - ${DATABASE_PORT} # Portal local e porta do docker
    volumes:
      - ./data:/var/lib/mysql
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "root:go_root_pass@(db:3306)/go_db?tls=false&parseTime=true"
      MYSQLD_EXPORTER_DISABLE_DEFAULT_METRICS: "false"
      MYSQLD_EXPORTER_SKIP_METRICS: "mysql_slave_.*,mysql_handler_*"
      EXTRA_OPTS: "--collect.perf_schema.cpu.eventsstatements=true --collect.perf_schema.memory.eventsstatements=true"
    ports:
      - 9104:9104
    depends_on:
      - db
volumes:
  grafana_data:
  prometheus_data:
