version: '3.8' # Versão do Docker Compose
services:
  mysql:
    image: ${DATABASE_IMAGE} # Imagem do banco de dados
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE} # Banco de dados
      MYSQL_USER: ${DATABASE_USER} # Usuário do banco de dados
      MYSQL_PASSWORD: ${DATABASE_PASSWORD} # Senha do banco de dados
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} # Senha root do banco de dados
    ports:
      - ${DATABASE_PORT} # Portal local e porta do docker
    volumes:
      - ./data:/var/lib/mysql
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  data:
  grafana_data:
