global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "mysql"
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ["mysql_exporter:9104"]
